import {
  Project,
  Partner,
  Milestone,
  Expense,
  Document,
  ProjectUpdate,
  ActivityLog,
  AIInsight,
  User,
  ProjectReport,
} from '@/types';

export const mockUsers: User[] = [
  {
    id: 'usr-1',
    email: 'admin@csr360.org',
    display_name: 'Aman Verma',
    avatar_url: null,
    role: 'admin',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-2',
    email: 'pria.sharma@csr360.org',
    display_name: 'Priya Sharma',
    avatar_url: null,
    role: 'member',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'usr-3',
    email: 'rajesh.kumar@csr360.org',
    display_name: 'Rajesh Kumar',
    avatar_url: null,
    role: 'member',
    created_at: '2026-02-01T00:00:00Z',
  },
];

export const mockPartners: Partner[] = [
  {
    id: 'ptn-1',
    name: 'Sanjeevani Education Foundation',
    type: 'ngo',
    contact_name: 'Dr. Sunita Deshmukh',
    contact_email: 'sunita@sanjeevani.org',
    contact_phone: '+91 98765 43210',
    website: 'https://sanjeevani-edu.org',
    description: 'Empowering rural youth through digital literacy and vocational skill development across Maharashtra and Gujarat.',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z',
    project_count: 2,
  },
  {
    id: 'ptn-2',
    name: 'Jal Shakti Water Trust',
    type: 'ngo',
    contact_name: 'Anil Kulkarni',
    contact_email: 'anil@jalshakti.org',
    contact_phone: '+91 98123 45678',
    website: 'https://jalshaktitrust.org',
    description: 'Community-led rainwater harvesting and solar-powered water filtration systems in drought-prone districts.',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-01-12T00:00:00Z',
    project_count: 2,
  },
  {
    id: 'ptn-3',
    name: 'National Skill Development Corp',
    type: 'government',
    contact_name: 'Vikram Singh',
    contact_email: 'vikram.singh@nsdc.gov.in',
    contact_phone: '+91 11 2345 6789',
    website: 'https://nsdcindia.org',
    description: 'Government agency collaborating on youth employment initiatives and certified technical workshops.',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-01-20T00:00:00Z',
    project_count: 1,
  },
  {
    id: 'ptn-4',
    name: 'GreenEarth Innovation Labs',
    type: 'corporate',
    contact_name: 'Meera Nair',
    contact_email: 'mnair@greenearth.io',
    contact_phone: '+91 80 4112 9900',
    website: 'https://greenearth.io',
    description: 'Corporate sustainability partner supplying solar micro-grids and energy audit solutions.',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
    project_count: 1,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'prj-1',
    title: 'Digital Literacy Centers in Rural Primary Schools',
    description: 'Setting up 25 solar-powered computer labs in government primary schools across Latur district, training 4,000+ children in basic computer skills, coding basics, and digital safety.',
    status: 'active',
    category: 'Digital Literacy',
    start_date: '2026-01-15',
    end_date: '2026-10-31',
    total_budget: 4500000,
    spent_budget: 2850000,
    partner_id: 'ptn-1',
    created_by: 'usr-1',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-02-15T14:30:00Z',
    partner: mockPartners[0],
    milestone_count: 4,
    completed_milestone_count: 2,
  },
  {
    id: 'prj-2',
    title: 'Solar-Powered Clean Water Stations',
    description: 'Installing 12 reverse osmosis (RO) filtration kiosks powered by rooftop solar panels to provide safe drinking water to over 15,000 villagers in drought-affected regions.',
    status: 'active',
    category: 'Water & Sanitation',
    start_date: '2026-02-01',
    end_date: '2026-11-30',
    total_budget: 6800000,
    spent_budget: 3400000,
    partner_id: 'ptn-2',
    created_by: 'usr-2',
    created_at: '2026-01-18T10:15:00Z',
    updated_at: '2026-03-01T11:00:00Z',
    partner: mockPartners[1],
    milestone_count: 5,
    completed_milestone_count: 2,
  },
  {
    id: 'prj-3',
    title: 'Women Micro-Entrepreneurship & Textile Skill Hub',
    description: 'Establishing vocational training centers for 500 rural women in handloom weaving, eco-friendly garment stitching, and financial management to enable self-employment.',
    status: 'planning',
    category: 'Women Empowerment',
    start_date: '2026-04-01',
    end_date: '2026-12-31',
    total_budget: 3200000,
    spent_budget: 450000,
    partner_id: 'ptn-3',
    created_by: 'usr-1',
    created_at: '2026-02-10T12:00:00Z',
    updated_at: '2026-02-28T09:20:00Z',
    partner: mockPartners[2],
    milestone_count: 3,
    completed_milestone_count: 0,
  },
  {
    id: 'prj-4',
    title: 'Afforestation & Biodiversity Corridor Project',
    description: 'Planting 50,000 native tree saplings across degraded forest lands, building soil moisture conservation trenches, and training local tribal youth as forest guardians.',
    status: 'active',
    category: 'Environment',
    start_date: '2026-01-01',
    end_date: '2026-09-30',
    total_budget: 5000000,
    spent_budget: 4100000,
    partner_id: 'ptn-4',
    created_by: 'usr-3',
    created_at: '2025-12-20T15:00:00Z',
    updated_at: '2026-03-02T16:45:00Z',
    partner: mockPartners[3],
    milestone_count: 4,
    completed_milestone_count: 3,
  },
  {
    id: 'prj-5',
    title: 'Mobile Primary Health Clinic Units',
    description: 'Deploying 3 custom-fitted ambulance vans equipped with diagnostic gear, tele-consultation screens, and essential medicines to serve 40 remote hamlets weekly.',
    status: 'completed',
    category: 'Healthcare',
    start_date: '2025-06-01',
    end_date: '2026-02-28',
    total_budget: 7500000,
    spent_budget: 7420000,
    partner_id: 'ptn-1',
    created_by: 'usr-2',
    created_at: '2025-05-15T08:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
    partner: mockPartners[0],
    milestone_count: 6,
    completed_milestone_count: 6,
  },
  {
    id: 'prj-6',
    title: 'Youth Vocational Robotics & STEM Program',
    description: 'Hands-on robotics kits, 3D printers, and STEM curriculum integration for 15 polytechnic institutes, fostering technical innovation and job readiness.',
    status: 'on_hold',
    category: 'Skill Development',
    start_date: '2026-03-01',
    end_date: '2026-11-15',
    total_budget: 2800000,
    spent_budget: 600000,
    partner_id: 'ptn-3',
    created_by: 'usr-1',
    created_at: '2026-02-15T11:30:00Z',
    updated_at: '2026-03-02T14:00:00Z',
    partner: mockPartners[2],
    milestone_count: 4,
    completed_milestone_count: 1,
  },
];

export const mockMilestones: Milestone[] = [
  // prj-1
  {
    id: 'mls-1',
    project_id: 'prj-1',
    title: 'School Survey & Infrastructure Readiness Audit',
    description: 'Audit 25 schools for electrical wiring, roof space for solar panels, and security.',
    due_date: '2026-02-15',
    status: 'completed',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-02-14T16:00:00Z',
  },
  {
    id: 'mls-2',
    project_id: 'prj-1',
    title: 'Hardware Procurement & Solar Installation',
    description: 'Procure 250 laptops, 25 solar array kits, and networking routers.',
    due_date: '2026-04-30',
    status: 'in_progress',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'mls-3',
    project_id: 'prj-1',
    title: 'Teacher Training Workshop & Curriculum Rollout',
    description: 'Train 50 school teachers on computer lab management and curriculum delivery.',
    due_date: '2026-07-15',
    status: 'pending',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'mls-4',
    project_id: 'prj-1',
    title: 'Mid-term Impact Assessment & Student Evaluation',
    description: 'Conduct baseline vs mid-term assessment of student computer literacy gains.',
    due_date: '2026-10-15',
    status: 'pending',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-10T09:00:00Z',
  },

  // prj-2
  {
    id: 'mls-5',
    project_id: 'prj-2',
    title: 'Water Quality Testing & Site Selection',
    description: 'Groundwater sampling across 20 prospective village locations to identify high fluorosis sites.',
    due_date: '2026-02-28',
    status: 'completed',
    created_at: '2026-01-18T10:15:00Z',
    updated_at: '2026-02-25T11:00:00Z',
  },
  {
    id: 'mls-6',
    project_id: 'prj-2',
    title: 'Construction of 6 Water Kiosks (Phase 1)',
    description: 'Civil works, shed installation, RO filtration machinery setup for initial 6 locations.',
    due_date: '2026-05-31',
    status: 'in_progress',
    created_at: '2026-01-18T10:15:00Z',
    updated_at: '2026-03-01T11:00:00Z',
  },
  {
    id: 'mls-7',
    project_id: 'prj-2',
    title: 'Community Water Committee Formation & Tariff Model',
    description: 'Form village-level maintenance committees and set minimal nominal maintenance fee structure.',
    due_date: '2026-03-10',
    status: 'overdue',
    created_at: '2026-01-18T10:15:00Z',
    updated_at: '2026-03-02T09:00:00Z',
  },
];

export const mockExpenses: Expense[] = [
  {
    id: 'exp-1',
    project_id: 'prj-1',
    category: 'Technology',
    amount: 1850000,
    description: 'Procurement of 250 refurbished educational laptops and heavy-duty battery backups.',
    date: '2026-02-05',
    receipt_url: null,
    created_by: 'usr-1',
    created_at: '2026-02-05T14:20:00Z',
    creator: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' },
  },
  {
    id: 'exp-2',
    project_id: 'prj-1',
    category: 'Infrastructure',
    amount: 720000,
    description: 'Solar panel roof mounting structures, inverters, and electrical cabling for 10 schools.',
    date: '2026-02-18',
    receipt_url: null,
    created_by: 'usr-2',
    created_at: '2026-02-18T11:00:00Z',
    creator: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
  {
    id: 'exp-3',
    project_id: 'prj-1',
    category: 'Travel & Logistics',
    amount: 280000,
    description: 'Transport of computer hardware and solar units from Pune warehouse to Latur sites.',
    date: '2026-02-24',
    receipt_url: null,
    created_by: 'usr-1',
    created_at: '2026-02-24T16:45:00Z',
    creator: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' },
  },
  {
    id: 'exp-4',
    project_id: 'prj-2',
    category: 'Infrastructure',
    amount: 2400000,
    description: 'Advance payment to AquaTech Systems for 12 commercial 1,000 LPH RO water plants.',
    date: '2026-02-10',
    receipt_url: null,
    created_by: 'usr-2',
    created_at: '2026-02-10T10:00:00Z',
    creator: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
  {
    id: 'exp-5',
    project_id: 'prj-2',
    category: 'Materials & Supplies',
    amount: 1000000,
    description: 'Solar array panels (3kW each) and smart metering hardware for water kiosks.',
    date: '2026-02-22',
    receipt_url: null,
    created_by: 'usr-2',
    created_at: '2026-02-22T15:30:00Z',
    creator: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    project_id: 'prj-1',
    name: 'School_Site_Readiness_Audit_Report.pdf',
    file_url: '#',
    file_type: 'application/pdf',
    file_size: 2450000,
    uploaded_by: 'usr-1',
    created_at: '2026-02-14T17:00:00Z',
    uploader: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' },
  },
  {
    id: 'doc-2',
    project_id: 'prj-1',
    name: 'Solar_Hardware_Vendor_Contract_2026.pdf',
    file_url: '#',
    file_type: 'application/pdf',
    file_size: 4120000,
    uploaded_by: 'usr-2',
    created_at: '2026-02-19T09:30:00Z',
    uploader: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
  {
    id: 'doc-3',
    project_id: 'prj-2',
    name: 'Hydrogeological_Survey_Latur_Dist.pdf',
    file_url: '#',
    file_type: 'application/pdf',
    file_size: 6800000,
    uploaded_by: 'usr-2',
    created_at: '2026-02-26T12:00:00Z',
    uploader: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
];

export const mockProjectUpdates: ProjectUpdate[] = [
  {
    id: 'upd-1',
    project_id: 'prj-1',
    title: '10 Solar Computer Labs Fully Operational!',
    content: 'We are thrilled to announce that Phase 1 installation across 10 rural schools in Latur block is complete. Over 1,200 students attended their first digital literacy orientation class this week.',
    author_id: 'usr-1',
    created_at: '2026-02-25T14:00:00Z',
    author: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' },
  },
  {
    id: 'upd-2',
    project_id: 'prj-1',
    title: 'Hardware Delivery Verified at Central Depot',
    content: 'All 250 laptops have passed Quality Assurance checks and received custom educational OS pre-loads including offline Wikipedia and STEM interactive modules.',
    author_id: 'usr-2',
    created_at: '2026-02-12T10:30:00Z',
    author: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
  {
    id: 'upd-3',
    project_id: 'prj-2',
    title: 'Phase 1 Water Filtration Kiosks Civil Work Initiated',
    content: 'Excavation and foundation work has started in 6 high-priority villages. Water samples have been re-verified by NABL accredited lab.',
    author_id: 'usr-2',
    created_at: '2026-03-01T09:15:00Z',
    author: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
];

export const mockActivityLog: ActivityLog[] = [
  {
    id: 'act-1',
    project_id: 'prj-1',
    user_id: 'usr-1',
    action: 'posted_update',
    entity_type: 'project_update',
    entity_id: 'upd-1',
    metadata: { title: '10 Solar Computer Labs Fully Operational!' },
    created_at: '2026-02-25T14:00:00Z',
    user: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' },
  },
  {
    id: 'act-2',
    project_id: 'prj-2',
    user_id: 'usr-2',
    action: 'logged_expense',
    entity_type: 'expense',
    entity_id: 'exp-5',
    metadata: { amount: 1000000, category: 'Materials & Supplies' },
    created_at: '2026-02-22T15:30:00Z',
    user: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' },
  },
  {
    id: 'act-3',
    project_id: 'prj-1',
    user_id: 'usr-1',
    action: 'completed_milestone',
    entity_type: 'milestone',
    entity_id: 'mls-1',
    metadata: { title: 'School Survey & Infrastructure Readiness Audit' },
    created_at: '2026-02-14T16:00:00Z',
    user: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' },
  },
  {
    id: 'act-4',
    project_id: 'prj-4',
    user_id: 'usr-3',
    action: 'updated_status',
    entity_type: 'project',
    entity_id: 'prj-4',
    metadata: { new_status: 'active' },
    created_at: '2026-02-01T10:00:00Z',
    user: { id: 'usr-3', display_name: 'Rajesh Kumar', email: 'rajesh.kumar@csr360.org' },
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: 'ins-1',
    title: 'Milestone Delay Risk: Water Tariff Committee Formation',
    summary: 'Project "Solar-Powered Clean Water Stations" has an overdue milestone for village water committee formation (due Mar 10, 2026). Delays in community governance could impact Phase 1 kiosk launch schedules.',
    severity: 'risk',
    data_points: [
      'Milestone overdue by 3 days',
      'Target budget spent: 50%',
      'Partner contact: Jal Shakti Water Trust',
    ],
    project_ids: ['prj-2'],
    generated_at: '2026-03-03T08:00:00Z',
  },
  {
    id: 'ins-2',
    title: 'Budget Variance Alert: Digital Literacy Centers',
    summary: '63.3% of total budget (₹28.5L / ₹45.0L) has been disbursed while 50% of milestones are complete. Transport costs were 12% above projected estimates.',
    severity: 'warning',
    data_points: [
      'Spent: ₹28,50,000 / ₹45,00,000',
      'Technology procurement is primary spend driver (₹18.5L)',
      'High solar panel unit cost variance detected',
    ],
    project_ids: ['prj-1'],
    generated_at: '2026-03-03T08:00:00Z',
  },
  {
    id: 'ins-3',
    title: 'Project On Hold: Youth Vocational Robotics Program',
    summary: 'Project "Youth Vocational Robotics & STEM Program" is currently on hold with only ₹6L disbursed out of ₹28L total budget. Partner agreement renewal with NSDC requires follow-up.',
    severity: 'warning',
    data_points: [
      'Status: On Hold',
      'Unallocated budget balance: ₹22,00,000',
      'Partner: National Skill Development Corp',
    ],
    project_ids: ['prj-6'],
    generated_at: '2026-03-03T08:00:00Z',
  },
  {
    id: 'ins-4',
    title: 'High ESG Impact & Budget Efficiency: Afforestation Project',
    summary: 'The Afforestation & Biodiversity Corridor project has achieved 75% of milestone completions with 82% budget efficiency. On track for early handover in Q3.',
    severity: 'positive',
    data_points: [
      'Milestone progress: 3/4 completed',
      '50,000 native saplings planted',
      'Community forest guardian training complete',
    ],
    project_ids: ['prj-4'],
    generated_at: '2026-03-03T08:00:00Z',
  },
];

export const mockReports: ProjectReport[] = [
  {
    id: 'rep-1',
    project_id: 'prj-1',
    title: 'Mid-Term Progress & Financial Audit Report Q1 2026.pdf',
    file_url: '#',
    file_type: 'application/pdf',
    file_size: 3200000,
    submitted_by: 'usr-1',
    created_at: '2026-02-28T10:00:00Z',
    summary_json: {
      key_achievements: [
        '10 solar-powered computer labs operational in Latur district schools.',
        '1,200 rural students enrolled in digital literacy and coding modules.',
        '250 ruggedized laptops procured with custom offline educational software.'
      ],
      important_issues: [
        'Intermittent solar battery backup failure in 2 remote school locations.',
        'Transport logistics cost exceeded Q1 budget line item by 12%.'
      ],
      financial_highlights: [
        'Total budget disbursed to date: ₹28,50,000 out of ₹45,00,000 (63.3%).',
        'Hardware procurement comprised 65% of Q1 total expenditure.'
      ],
      next_actions: [
        'Procure heavy-duty voltage stabilizers for schools with erratic grid access.',
        'Commence Phase 2 teacher training workshops in March 2026.'
      ],
      generated_at: '2026-03-01T12:00:00Z'
    },
    submitter: { id: 'usr-1', display_name: 'Aman Verma', email: 'admin@csr360.org' }
  },
  {
    id: 'rep-2',
    project_id: 'prj-2',
    title: 'Water Quality & Site Feasibility Report.pdf',
    file_url: '#',
    file_type: 'application/pdf',
    file_size: 4500000,
    submitted_by: 'usr-2',
    created_at: '2026-02-20T14:30:00Z',
    summary_json: {
      key_achievements: [
        'NABL accredited lab verification completed for 12 village water sources.',
        '6 village panchayats signed land lease agreements for kiosk setup.'
      ],
      important_issues: [
        'High total dissolved solids (TDS) in 2 villages require multi-stage RO membranes.',
        'Overdue milestone for local village water committee formation.'
      ],
      financial_highlights: [
        'Advance payment of ₹24,00,000 released for 12 RO water plant units.',
        'Total expenditure to date: ₹34,00,000 (50.0% of total budget).'
      ],
      next_actions: [
        'Conduct community meetings to expedite water committee elections by Mar 15.',
        'Finalize solar rooftop structure installation schedules with GreenEarth Labs.'
      ],
      generated_at: '2026-02-21T09:00:00Z'
    },
    submitter: { id: 'usr-2', display_name: 'Priya Sharma', email: 'pria.sharma@csr360.org' }
  }
];
